import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

import { Home } from '@/components/screens/home/Home'

const HomePage: NextPage = () => {
	return (
		<div>
			<Home />
			{/* <Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link rel="preconnect" href="https://fonts.gstatic.com" />
				<link
					href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@400;600;700&display=swap"
					rel="stylesheet"
				/>
			</Head>
			<h1>Привет новое приложение...</h1>
			<Link href="/">Hello 20/02 Academy</Link> */}
			<h1>Home page</h1>
		</div>
	)
}

export default Home
