import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link rel="preconnect" href="https://fonts.gstatic.com" />
				<link
					href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@400;600;700&display=swap"
					rel="stylesheet"
				/>
			</Head>
			<h1>Привет новое приложение...</h1>
			<Link href="/">Hello 20/02 Academy</Link>
		</>
	)
}

export default Home
